### ISSUE TITLE
curl -OL https://storage.googleapis.com/private.delegatecall.com/loom/linux/build-163/loom

### ISSUE THREAD

**Issue by hina90** [loomnetwork/tiles-chain#4]
Mainland China needs over the wall for access  https://storage.googleapis.com/private.delegatecall.com/loom/osx/build-132/loom .......?

**Comment by hina90** [comment]
This is the result
[root@localhost ~]# sudo unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d /usr/local
Archive:  protoc-3.5.1-linux-x86_64.zip
   creating: /usr/local/include/google/
   creating: /usr/local/include/google/protobuf/
  inflating: /usr/local/include/google/protobuf/struct.proto  
  inflating: /usr/local/include/google/protobuf/type.proto  
  inflating: /usr/local/include/google/protobuf/descriptor.proto  
  inflating: /usr/local/include/google/protobuf/api.proto  
  inflating: /usr/local/include/google/protobuf/empty.proto  
   creating: /usr/local/include/google/protobuf/compiler/
  inflating: /usr/local/include/google/protobuf/compiler/plugin.proto  
  inflating: /usr/local/include/google/protobuf/any.proto  
  inflating: /usr/local/include/google/protobuf/field_mask.proto  
  inflating: /usr/local/include/google/protobuf/wrappers.proto  
  inflating: /usr/local/include/google/protobuf/timestamp.proto  
  inflating: /usr/local/include/google/protobuf/duration.proto  
  inflating: /usr/local/include/google/protobuf/source_context.proto  
  inflating: /usr/local/bin/protoc   
  inflating: /usr/local/readme.txt   
[root@localhost ~]# sudo chmod +x /usr/local/bin/protoc
[root@localhost ~]# curl -OL https://storage.googleapis.com/private.delegatecall.com/loom/linux/build-163/loom
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed to connect to 2404:6800:4008:802::2010: 网络不可达

**Comment by HangYang** [comment]
yes, you need a VPN. Sorry about this.

**Comment by hina90** [comment]
ok, thanks.
