### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qazujmko** [loomnetwork/tiles-chain#5]
ERROR in /root/tiles-chain/webclient/node_modules/loom-js/dist/crypto-utils.d.ts
(40,54): error TS2304: Cannot find name 'Buffer'.

ERROR in /root/tiles-chain/webclient/node_modules/loom-js/dist/crypto-utils.d.ts
(1,23): error TS2688: Cannot find type definition file for 'node'.

ERROR in /root/tiles-chain/webclient/node_modules/loom-js/dist/evm-contract.d.ts
(1,23): error TS2688: Cannot find type definition file for 'node'.

ERROR in /root/tiles-chain/webclient/node_modules/loom-js/dist/contract.d.ts
(1,23): error TS2688: Cannot find type definition file for 'node'.

ERROR in /root/tiles-chain/webclient/node_modules/loom-js/dist/internal/json-rpc-client.d.ts
(1,23): error TS2688: Cannot find type definition file for 'node'.

ERROR in /root/tiles-chain/webclient/node_modules/loom-js/dist/client.d.ts
(1,23): error TS2688: Cannot find type definition file for 'node'.

**Comment by PaulRBerg** [comment]
+1

**Comment by mattkanwisher** [comment]
please run the following from the readme
```
# On second terminal
cd tiles-chain/webclient

# Install
yarn

# Compile protobuf
yarn run proto
```
