### ISSUE TITLE
can't proceed after make deps

### ISSUE THREAD

**Issue by WarisRao** [loomnetwork/tiles-chain#7]
make
protoc --plugin=./protoc-gen-gogo -Isrc -I/usr/local/include --gogo_out=src src/types/types.proto
make: protoc: No such file or directory
make: *** [src/types/types.pb.go] Error 1

**Comment by mattkanwisher** [comment]
You don't have Protoc installed. Please follow the prereqs http://loomx.io/developers/docs/en/prereqs.html
